app = 'backend-bitter-log-4782'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  max_machines_running = 1  # Added this line to limit to 1 machine

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1